React capstone project - Metrics webapp
brainskev/Covid19_Tracking_App pull request #1
Opened 2023-02-25 17:33 UTC by brainskev

In this milestone I achieved the following
-     Selected the covid19 API.
-     Built file structure for my React app.
-     Prepared routes and navigation in my app.
-     Created the home page and the details page.
-     Made sure that a user can display a list of items and filter them with data that came from the API.
-     Created the tests for the application.
-     Styled my components to match the design provided.
-     Deployed the project and tested for final details.
-     Recorded a video for my project.

2023-02-25 20:04 UTC, zieeco requested changes
Hi @brainskev ,


Great job so far! 👏 
You've done well, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- No linter errors.✔️
- Test passed :heavy_check_mark: 
- Nice design. ✔️
- Descriptive PR. ✔️
- Good commit message :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._


<img src="https://media0.giphy.com/media/8UGVQESpDMMQl7yd3F/giphy.gif"/>


## Optional suggestions
- N/A


**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-25 20:04 UTC, zieeco commented on src/pages/Details.js
> +export default Home;
- Hey, great job. I think you've made a little oversight here, kindly double-check the `Home` and `Details` page as you've duplicated the `Home` for the `Details` page and this is not making your details page work as expected compared to the design template. Please, kindly check them again to implement the details page as much as you can. See the image below to see the missing part you're yet to have implemented:



![Screenshot from 2023-02-25 20-35-58](https://user-images.githubusercontent.com/59397159/221376251-71fa73f8-7308-43e9-bfec-3a481fd4bf7e.png)

2023-02-25 20:04 UTC, zieeco commented on README.md
> +
- Hey, let's also give appropriate credit to [Nelson Sakwa](https://www.behance.net/sakwadesignstudio) the [author of the original design](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)), as required by the [Creative Commons License](https://creativecommons.org/licenses/).

2023-02-25 20:04 UTC, zieeco commented on README.md
> +  - [Prerequisites](#prerequisites)
- Hey, Please, let's also add the prerequisites section in the readme to point out the basic things users must or should have to be able to run the project locally on their machine.

2023-02-25 20:04 UTC, zieeco commented on README.md
> +- [❓ FAQ (OPTIONAL)](#faq)
- Hey, since this section is not in the readme, let's kindly remove it to keep our readme more professional by not having a broken link.

2023-02-25 20:04 UTC, zieeco commented on README.md
> +## 🚀 Live Demo <a name="live-demo"></a>
- Hey, while you've added the live demo, please remember to add the video presentation as you've not added any yet. Please refer to the project requirement to follow the instructions on adding the video, pay attention to the length, and highlight some pieces of code you find interesting in your IDE.
- You can add the video in the PR's description or just after the live demo link.

2023-02-25 20:04 UTC, zieeco commented on src/tests/Details.test.js
> +});
- Hey, according to my review on the `Details` page, please, not that your test for `Home` and `Details` page are the same because of the duplicate you've made on the Details page, duplicating the `Home` component in the Details page. Please, try fix the issue in the Details page UI to update your test.

2023-02-25 20:04 UTC, zieeco commented on src/App.css
>  }
- Hey, please, kindly remove the blue decoration color as this make your design inconsistent with the original design. I see you removed it on hover, please, it shouldn't be there in any state of interaction from the user.


![Screenshot from 2023-02-25 20-55-41](https://user-images.githubusercontent.com/59397159/221377095-1689d28a-3c1d-4c24-b812-396a48edc3f4.png)

2023-02-26 00:24 UTC, andersonlebon approved these changes
## Hi @brainskev 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![nodding-yes](https://user-images.githubusercontent.com/65068771/143095390-344d1cb0-b853-4b91-8662-5d9049dc9e60.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question `@andersonlebon` so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-26 22:40 UTC, merged

2023-04-17 09:13 UTC, amejid reviewed
Hi @brainskev, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/RltjLEzzB87ErJdxHz/giphy.gif"/>

## Highlights
- Linter checks passing :heavy_check_mark: 
- Correct workflow :heavy_check_mark: 
- Good UI design :heavy_check_mark: 
- All functionalities working as expected :heavy_check_mark: 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._